/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.dtu.imm.distributedsystems.projects.sensornetwork.admin.gui;

import java.awt.Color;

import dk.dtu.imm.distributedsystems.projects.sensornetwork.admin.components.TransceiverComponent;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.Packet;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.PacketGroup;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.PacketType;

/**
 *
 * @author mkucharek
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form AdminFrame
     */
    public AdminFrame(TransceiverComponent transceiver) {
    	this.transceiver = transceiver;
        initComponents();
    }
    
    public void showReport(Packet p) {
    	this.titleLabel.setText(p.getType().toString());
    	this.valueTextField.setText(p.getValue());
    }
    
    public void showAlarmData(Packet p) {
    	// too verbose
    	//JOptionPane.showMessageDialog(jTabbedPane1, "Temperature in sensor " + p.getSrcNodeId() + " is now " + p.getValue() + "!", "Alert", JOptionPane.WARNING_MESSAGE);
    	
    	this.alertLabel.setText("Temperature in sensor " + p.getSrcNodeId() + " is now " + p.getValue() + "!");
    	
    	if(this.alertLabel.getForeground().equals(Color.BLUE)) {
    		this.alertLabel.setForeground(Color.RED);
    	} else {
    		this.alertLabel.setForeground(Color.BLUE);
    	}
    
    }
    
    public void showError(Packet p) {
    	
    	String msg = "Sink is not responding";
    	if(PacketGroup.COMMAND.equals(p.getGroup())) {
    		setLabel.setText(msg);
    	} else if(PacketGroup.QUERY.equals(p.getGroup())) {
    		valueTextField.setText(msg);
    	}
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        avgButton = new javax.swing.JButton();
        valueTextField = new javax.swing.JTextField();
        minButton = new javax.swing.JButton();
        maxButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        setTextField = new javax.swing.JTextField();
        setLabel = new javax.swing.JLabel();
        thresholdButton = new javax.swing.JRadioButton();
        periodButton = new javax.swing.JRadioButton();
        setButton = new javax.swing.JButton();
        alertLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Node Client ");
        setResizable(false);

        jPanel1.setOpaque(false);

        titleLabel.setText("Click a button");

        avgButton.setText("AVG");
        avgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgButtonActionPerformed(evt);
            }
        });

        valueTextField.setEnabled(false);

        minButton.setText("MIN");
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });

        maxButton.setText("MAX");
        maxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(maxButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(minButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(avgButton))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(titleLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(valueTextField)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(44, 44, 44)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(valueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(titleLabel))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(maxButton)
                    .add(minButton)
                    .add(avgButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPanel1);

        jPanel2.setOpaque(false);

        buttonGroup1.add(thresholdButton);
        thresholdButton.setText("Threshold");

        buttonGroup1.add(periodButton);
        periodButton.setText("Period");

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(thresholdButton)
                        .add(18, 18, 18)
                        .add(periodButton)
                        .add(0, 92, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(setTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(setButton))
                    .add(setLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .add(setLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(setTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(thresholdButton)
                    .add(periodButton))
                .add(33, 33, 33))
        );

        jTabbedPane1.addTab("Config", jPanel2);

        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertLabel.setText("Alert messages will appear here");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(alertLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(alertLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    private void maxButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.MAX));
    	titleLabel.setText("MAX");
    	valueTextField.setText("Request pending...");
    }

    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.MIN));
    	titleLabel.setText("MIN");
		valueTextField.setText("Request pending...");
    }

    private void avgButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.AVG));
    	titleLabel.setText("AVG");
    	valueTextField.setText("Request pending...");
    }

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
    	if(setTextField.getText() == null) {
    		setLabel.setText("Please enter a value");
    		return;
    	}
    	
    	try {
    		Integer.parseInt(setTextField.getText());
    	} catch (NumberFormatException e) {
    		// incorrect input
    		setLabel.setText("Please choose a numeric value");
    		return;
    	}
    	
    	// all set - perform desired action
    	if(periodButton.isSelected()) {
    		transceiver.handlePacket(new Packet("ADMIN", PacketType.PRD, setTextField.getText()));
    		setLabel.setText("Period changed to " + setTextField.getText());
    		setTextField.setText("");
    	} else if (thresholdButton.isSelected()) {
    		transceiver.handlePacket(new Packet("ADMIN", PacketType.THR, setTextField.getText()));
    		setLabel.setText("Threshold changed to " + setTextField.getText());
    		setTextField.setText("");
    	}
    	
    }

    // core declaration
    private TransceiverComponent transceiver;
    
    // Variables declaration - do not modify
    private javax.swing.JLabel alertLabel;
    private javax.swing.JButton avgButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton maxButton;
    private javax.swing.JButton minButton;
    private javax.swing.JRadioButton periodButton;
    private javax.swing.JButton setButton;
    private javax.swing.JLabel setLabel;
    private javax.swing.JTextField setTextField;
    private javax.swing.JRadioButton thresholdButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration
}
