/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.dtu.imm.distributedsystems.projects.sensornetwork.admin.gui;

import dk.dtu.imm.distributedsystems.projects.sensornetwork.admin.components.TransceiverComponent;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.Packet;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.PacketType;

/**
 *
 * @author mkucharek
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form AdminFrame
     */
    public AdminFrame(TransceiverComponent transceiver) {
    	this.transceiver = transceiver;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        maxButton = new javax.swing.JButton();
        minButton = new javax.swing.JButton();
        avgButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        setTextField = new javax.swing.JTextField();
        periodButton = new javax.swing.JRadioButton();
        thresholdButton = new javax.swing.JRadioButton();
        setButton = new javax.swing.JButton();
        setLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maxButton.setText("MAX");
        maxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxButtonActionPerformed(evt);
            }
        });

        minButton.setText("MIN");
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });

        avgButton.setText("AVG");
        avgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgButtonActionPerformed(evt);
            }
        });

        titleLabel.setText("Click a button");

        valueTextField.setEnabled(false);

        buttonGroup1.add(periodButton);
        periodButton.setText("Period");

        buttonGroup1.add(thresholdButton);
        thresholdButton.setText("Threshold");

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(titleLabel)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(setLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(maxButton)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(valueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(minButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(setTextField))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(avgButton))))
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(periodButton)
                        .add(18, 18, 18)
                        .add(thresholdButton))
                    .add(layout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(setButton)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleLabel)
                    .add(valueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(maxButton)
                    .add(minButton)
                    .add(avgButton))
                .add(57, 57, 57)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(setTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(periodButton)
                    .add(thresholdButton))
                .add(18, 18, 18)
                .add(setButton)
                .add(0, 23, Short.MAX_VALUE))
        );

        pack();
    }

    private void maxButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.MAX));
		valueTextField.setText("MAX request sent");
    }

    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.MIN));
		valueTextField.setText("MIN request sent");
    }

    private void avgButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.AVG));
		valueTextField.setText("AVG request sent");
    }

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
    	if(setTextField.getText() == null) {
    		setLabel.setText("Please enter a value");
    		return;
    	}
    	
    	try {
    		Integer.parseInt(setTextField.getText());
    	} catch (NumberFormatException e) {
    		// incorrect input
    		setLabel.setText("Please choose a numeric value");
    		return;
    	}
    	
    	// all set - perform desired action
    	if(periodButton.isSelected()) {
    		transceiver.handlePacket(new Packet("ADMIN", PacketType.PRD, setTextField.getText()));
    		setLabel.setText("Period changed to " + setTextField.getText());
    		setTextField.setText("");
    	} else if (thresholdButton.isSelected()) {
    		transceiver.handlePacket(new Packet("ADMIN", PacketType.THR, setTextField.getText()));
    		setLabel.setText("Threshold changed to " + setTextField.getText());
    		setTextField.setText("");
    	}
    	
    }

    // core declaration
    private TransceiverComponent transceiver;
    
    // Variables declaration - do not modify
    private javax.swing.JButton avgButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton maxButton;
    private javax.swing.JButton minButton;
    private javax.swing.JRadioButton periodButton;
    private javax.swing.JButton setButton;
    private javax.swing.JLabel setLabel;
    private javax.swing.JTextField setTextField;
    private javax.swing.JRadioButton thresholdButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration
}
