/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.dtu.imm.distributedsystems.projects.sensornetwork.admin.gui;

import java.awt.Color;

import dk.dtu.imm.distributedsystems.projects.sensornetwork.admin.components.TransceiverComponent;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.Packet;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.PacketGroup;
import dk.dtu.imm.distributedsystems.projects.sensornetwork.common.packet.PacketType;

/**
 * The Class AdminFrame.
 *
 * @author Maciej Kucharek <a href="mailto:s091828 (at) student.dtu.dk">s091828 (at) student.dtu.dk</a>
 */
public class AdminFrame extends javax.swing.JFrame {

    /** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Creates new form AdminFrame.
	 *
	 * @param transceiver the transceiver
	 */
    public AdminFrame(TransceiverComponent transceiver) {
    	this.transceiver = transceiver;
        initComponents();
    }
    
    /**
     * Show report.
     *
     * @param p the p
     */
    public void showReport(Packet p) {
    	this.titleLabel.setText(p.getType().toString());
    	if (p.getValue().length() != 0) {
    		this.valueTextField.setText(p.getValue());
    	} else {
    		this.valueTextField.setText("N/A");
    	}
    }
    
    /**
     * Show alarm data.
     *
     * @param p the p
     */
    public void showAlarmData(Packet p) {
    	// too verbose
    	//JOptionPane.showMessageDialog(jTabbedPane1, "Temperature in sensor " + p.getSrcNodeId() + " is now " + p.getValue() + "!", "Alert", JOptionPane.WARNING_MESSAGE);
    	
    	this.alertLabel.setText("Temperature in sensor " + p.getSrcNodeId() + " is now " + p.getValue() + "!");
    	
    	if(this.alertLabel.getForeground().equals(Color.BLUE)) {
    		this.alertLabel.setForeground(Color.RED);
    	} else {
    		this.alertLabel.setForeground(Color.BLUE);
    	}
    
    }
    
    /**
     * Show error.
     *
     * @param p the p
     */
    public void showError(Packet p) {
    	
    	String msg = "Sink is not responding";
    	if(PacketGroup.COMMAND.equals(p.getGroup())) {
    		setLabel.setText(msg);
    	} else if(PacketGroup.QUERY.equals(p.getGroup())) {
    		valueTextField.setText(msg);
    	}
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        maxButton = new javax.swing.JButton();
        minButton = new javax.swing.JButton();
        avgButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        setTextField = new javax.swing.JTextField();
        setLabel = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        periodButton = new javax.swing.JRadioButton();
        thresholdButton = new javax.swing.JRadioButton();
        alertLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Node Client ");
        setResizable(false);

        jTabbedPane1.setOpaque(true);

        jPanel1.setOpaque(false);

        titleLabel.setText("Click a button");

        valueTextField.setEnabled(false);

        jPanel3.setOpaque(false);

        maxButton.setText("MAX");
        maxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxButtonActionPerformed(evt);
            }
        });
        jPanel3.add(maxButton);

        minButton.setText("MIN");
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });
        jPanel3.add(minButton);

        avgButton.setText("AVG");
        avgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgButtonActionPerformed(evt);
            }
        });
        jPanel3.add(avgButton);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, titleLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(valueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(titleLabel)
                .add(16, 16, 16)
                .add(valueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPanel1);

        jPanel2.setOpaque(false);

        setLabel.setText("Configuration");

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        jPanel4.setOpaque(false);

        buttonGroup1.add(periodButton);
        periodButton.setText("Period");
        jPanel4.add(periodButton);

        buttonGroup1.add(thresholdButton);
        thresholdButton.setText("Threshold");
        jPanel4.add(thresholdButton);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(setTextField)
                .add(18, 18, 18)
                .add(setButton))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(setLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(0, 18, Short.MAX_VALUE)
                .add(setLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(setButton)
                    .add(setTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Config", jPanel2);

        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertLabel.setText("Alert messages will appear here");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(alertLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(alertLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    /**
     * Max button action performed.
     *
     * @param evt the evt
     */
    private void maxButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.MAX));
    	titleLabel.setText("MAX");
    	valueTextField.setText("Request pending...");
    }

    /**
     * Min button action performed.
     *
     * @param evt the evt
     */
    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.MIN));
    	titleLabel.setText("MIN");
		valueTextField.setText("Request pending...");
    }

    /**
     * Avg button action performed.
     *
     * @param evt the evt
     */
    private void avgButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	transceiver.handlePacket(new Packet("ADMIN", PacketType.AVG));
    	titleLabel.setText("AVG");
    	valueTextField.setText("Request pending...");
    }

    /**
     * Sets the button action performed.
     *
     * @param evt the new button action performed
     */
    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
    	if(setTextField.getText() == null) {
    		setLabel.setText("Please enter a value");
    		return;
    	}
    	
    	try {
    		Integer.parseInt(setTextField.getText());
    	} catch (NumberFormatException e) {
    		// incorrect input
    		setLabel.setText("Please choose a numeric value");
    		return;
    	}
    	
    	// all set - perform desired action
    	if(periodButton.isSelected()) {
    		transceiver.handlePacket(new Packet("ADMIN", PacketType.PRD, setTextField.getText()));
    		setLabel.setText("Period changed to " + setTextField.getText());
    		setTextField.setText("");
    	} else if (thresholdButton.isSelected()) {
    		transceiver.handlePacket(new Packet("ADMIN", PacketType.THR, setTextField.getText()));
    		setLabel.setText("Threshold changed to " + setTextField.getText());
    		setTextField.setText("");
    	}
    	
    }

    // core declaration
    /** The transceiver. */
    private TransceiverComponent transceiver;
    
    // Variables declaration - do not modify
    /** The alert label. */
    private javax.swing.JLabel alertLabel;
    
    /** The avg button. */
    private javax.swing.JButton avgButton;
    
    /** The button group1. */
    private javax.swing.ButtonGroup buttonGroup1;
    
    /** The j panel1. */
    private javax.swing.JPanel jPanel1;
    
    /** The j panel2. */
    private javax.swing.JPanel jPanel2;
    
    /** The j panel3. */
    private javax.swing.JPanel jPanel3;
    
    /** The j panel4. */
    private javax.swing.JPanel jPanel4;
    
    /** The j tabbed pane1. */
    private javax.swing.JTabbedPane jTabbedPane1;
    
    /** The max button. */
    private javax.swing.JButton maxButton;
    
    /** The min button. */
    private javax.swing.JButton minButton;
    
    /** The period button. */
    private javax.swing.JRadioButton periodButton;
    
    /** The set button. */
    private javax.swing.JButton setButton;
    
    /** The set label. */
    private javax.swing.JLabel setLabel;
    
    /** The set text field. */
    private javax.swing.JTextField setTextField;
    
    /** The threshold button. */
    private javax.swing.JRadioButton thresholdButton;
    
    /** The title label. */
    private javax.swing.JLabel titleLabel;
    
    /** The value text field. */
    private javax.swing.JTextField valueTextField;
}
